package com.cybersecuals.gridgarrison.trust.contract;

import org.web3j.protocol.Web3j;
import org.web3j.crypto.Credentials;
import org.web3j.tx.Contract;
import org.web3j.tx.gas.ContractGasProvider;
import org.web3j.protocol.core.RemoteCall;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import org.web3j.abi.TypeReference;
import org.web3j.abi.datatypes.*;

import java.util.Arrays;
import java.util.Collections;

/**
 * Web3j Java wrapper for the {@code FirmwareRegistry} smart contract.
 * Package-private — only {@code BlockchainServiceImpl} uses this directly.
 *
 * In a real project this class is auto-generated by the Web3j CLI from the
 * compiled ABI + bytecode:
 *   web3j generate solidity -a FirmwareRegistry.abi -b FirmwareRegistry.bin \
 *       -o src/main/java -p com.cybersecuals.gridgarrison.trust.contract
 *
 * Solidity interface (conceptual):
 * <pre>
 * function getGoldenHash(string calldata stationId) external view returns (string memory);
 * function registerGoldenHash(string calldata stationId,
 *                              string calldata goldenHash) external;
 * </pre>
 */
public class FirmwareRegistryContract extends Contract {

    public static final String BINARY = "0x"; // replace with compiled bytecode

    protected FirmwareRegistryContract(String contractAddress,
                                        Web3j web3j,
                                        Credentials credentials,
                                        ContractGasProvider gasProvider) {
        super(BINARY, contractAddress, web3j, credentials, gasProvider);
    }

    // -------------------------------------------------------------------------
    // Factory
    // -------------------------------------------------------------------------

    public static FirmwareRegistryContract load(String contractAddress,
                                                 Web3j web3j,
                                                 Credentials credentials,
                                                 ContractGasProvider gasProvider) {
        return new FirmwareRegistryContract(contractAddress, web3j, credentials, gasProvider);
    }

    // -------------------------------------------------------------------------
    // Read functions
    // -------------------------------------------------------------------------

    /**
     * Calls {@code getGoldenHash(stationId)} — view function, no gas.
     */
    public RemoteCall<String> getGoldenHash(String stationId) {
        final Function function = new Function(
            "getGoldenHash",
            Arrays.asList(new Utf8String(stationId)),
            Collections.singletonList(new TypeReference<Utf8String>() {})
        );
        return executeRemoteCallSingleValueReturn(function, String.class);
    }

    // -------------------------------------------------------------------------
    // Write functions
    // -------------------------------------------------------------------------

    /**
     * Calls {@code registerGoldenHash(stationId, goldenHash)}.
     * Submits a signed transaction — costs gas.
     */
    public RemoteCall<TransactionReceipt> registerGoldenHash(String stationId,
                                                              String goldenHash) {
        final Function function = new Function(
            "registerGoldenHash",
            Arrays.asList(
                new Utf8String(stationId),
                new Utf8String(goldenHash)
            ),
            Collections.emptyList()
        );
        return executeRemoteCallTransaction(function);
    }
}
