#!/bin/bash
set -e

echo "GridGarrison Person 1 Startup (current)"
echo ""

echo "1) Build"
echo "cd /path/to/gridgarrison && mvn -DskipTests compile"
echo "cd /path/to/gridgarrison && mvn -f ev-simulator/simulator-app/pom.xml -DskipTests compile"
echo ""
echo "2) Run backend (demo-mtls, port 8443)"
echo "Set GG_* environment variables for your shell (mirror scripts/local-env.ps1 values)"
echo "cd /path/to/gridgarrison && mvn spring-boot:run \"-Dspring-boot.run.profiles=demo-mtls\""
echo ""
echo "3) Run simulator (port 8082)"
echo "cd /path/to/gridgarrison && mvn -f ev-simulator/simulator-app/pom.xml spring-boot:run \"-Dspring-boot.run.profiles=demo-mtls\""
echo ""
echo "4) Smoke test"
echo "curl http://localhost:8082/api/ev/status"
echo "curl -X POST 'http://localhost:8082/api/ev/user/flow/reset?clearIntent=true&resetWallet=false&resetBattery=false'"
echo "curl 'http://localhost:8082/api/ev/user/flow/status?refreshTrust=true'"
echo ""
echo "5) Open dashboards"
echo "https://localhost:8443/visualizer.html"
echo "https://localhost:8443/panel.html"
echo "http://localhost:8082/ev-dashboard.html"
